Task 3 forms directives pipes
OlympiqueB/angular-fundamentals-template pull request #3
Opened 2024-10-05 15:19 UTC by OlympiqueB

Almost half of the Autocode tests fail, but the components seem to be working.
Some of them were not completely clear to me, but I've tried to implement them based on the task instructions.

2024-10-08 08:22 UTC, TamasViczian commented on src/app/shared/components/course-form/course-form.component.ts
> +  constructor(
Hmmm, I think these constructor params can be assigned private visibility

2024-10-08 08:24 UTC, TamasViczian commented on src/app/shared/components/course-form/course-form.component.ts
> +      console.log(newCourse);
you can delete

2024-10-08 08:24 UTC, TamasViczian commented on src/app/shared/components/course-form/course-form.component.ts
> +      console.log(newAuthor);
delete

2024-10-08 08:30 UTC, TamasViczian commented on src/app/shared/components/course-form/course-form.component.html
A few observations on functionality:

Once I click the create course button without the form filled out, here is the UI update. I guess it is not compulsory to enter an author name - surely it is ok to select some author(s) from the list. But 'Course Authors' does not give any feedback on no authors added to the course.
![image](https://github.com/user-attachments/assets/19961aad-2e2d-4af9-bb32-da0f2c4d707d)

I think whitespace character is allowed to add in the Author create field.
![image](https://github.com/user-attachments/assets/21fa1097-e8ad-461a-9d2d-b299f5390ea5)

2024-10-08 08:40 UTC, TamasViczian commented on src/app/shared/components/login-form/login-form.component.html
I see that the once I hit login button, the console logs the credentials and the UI is updated like below.
- probably we don't want to log the user password anywhere as that can be a major security threat.
- form can be reset, instead of invalid status
![image](https://github.com/user-attachments/assets/e468a5ca-a175-461a-82bf-12a1ad7c01a3)

2024-10-08 08:40 UTC, TamasViczian commented on src/app/shared/components/login-form/login-form.component.ts
> +      console.log(loginUser);
delete

2024-10-08 08:43 UTC, TamasViczian commented on src/app/shared/components/registration-form/registration-form.component.ts
> +      console.log(newUser);
delete?

2024-10-08 08:47 UTC, TamasViczian requested changes
Really nice job! There are a few updates you might want to consider.
As I see you are getting along with the task pretty good, I suggest you implement the extra task with password show/hide. Thanks

2024-10-08 11:11 UTC, OlympiqueB commented
Hi,

Thanks for the review and the comments.
I think I've addressed the issues.

I also added the directive for password toggle, which I applied to the login-form component. The styling and the icon implementation might be a bit messy. It would probably make more sense to create a separate icon service for handling this, but this was made in a hurry, just to test and show that the directive is working.

2024-10-09 06:37 UTC, TamasViczian commented on src/app/shared/components/login-form/login-form.component.ts
> +    {
Double curly braces?

2024-10-09 06:39 UTC, TamasViczian approved these changes
Good, approved. Just delete the duplicated curly braces on LoginFormComponent constructor.

2024-10-09 20:06 UTC, merged